### ISSUE TITLE
Newly documented duplicates api call.  Can't get listing?

### ISSUE THREAD

**Issue by go1dfish** [trevorsenior/snoocore#87] opened 2015-02-07 07:43 UTC
http://www.reddit.com/dev/api#GET_{article}_duplicates

This was recently added to the reddit api docs.  I tried accessing it in snoocore with 

reddit('/' + id + '/duplicates/').listing()

But snoocore tells me it's not a valid path.

This is the last non OAUTH api call I'm using.

Could you help me figure out how to use this newly documented api in Snoocore?

**Comment by trevorsenior** [comment] 2015-02-07 18:05
Ah missed that notice. I am usually pretty good when it comes to checking /r/redditdev

Basically all this needs is a run of this command (root of the Snoocore repository): 

```javascript
./run.js api
```

and it will automatically fetch & rebuild the latest api from the documentation.

I'll run that command and push it in `v2.5.0` which I'll release in the next hour or so. If you can't wait, feel free to run the above command in your current install of Snoocore.

You can also make use of `reddit.raw` for it, but that would be a bit ugly!

http://tsenior.com/snoocore/undocumentedEndpoints.html

I'll close this issue once it's in the library. Thanks for reporting it!

**Comment by go1dfish** [comment] 2015-02-07 19:22
Yeah I'm using the raw request (and unauthed) for now and have been for quite a few days (and it has been a bit ugly).

https://github.com/go1dfish/politic-bot/blob/master/lib/main.js#L104

But it's been working well enough, except for private subs (My bot reported some erroneous removals from /r/CenturyClub when the high karma club started getting political)

**Comment by trevorsenior** [comment] 2015-02-07 23:09
Still writing the tests for issue #82 -- it's nearly there but having some delays. I'm relying heavily on the *or so* of my last message :wink:

**Comment by go1dfish** [comment] 2015-02-08 04:10
Will be worth the wait if we get automatic retries :)

**Comment by go1dfish** [comment] 2015-02-09 04:44
Snoocore is still giving me invalid path for this:


reddit('/' + id + '/duplicates/').listing()

Results in:

    Error: Invalid path provided. Check that this is a valid path.
    2v9o9b/duplicates

How should I be accessing this call with snoocore?

**Comment by damianb** [comment] 2015-02-09 16:43
In the meantime, there's the reddit.raw() thing iirc. [I use that for undocumented endpoints](https://github.com/damianb/trainerred/blob/master/src/lib.js#L188).

**Comment by go1dfish** [comment] 2015-02-09 17:21
Yeah already using raw here, just looking forward to being able to move my last raw call to standard OAUTH.

Also, even with raw I've not figured out a way to make an authed call to this endpoint with snoocore.

But this isn't a huge blocker for anything in the short term because the raw call works well enough for my purposes right now.

I just need a way to do this before OAUTH goes mandatory, and before I will consider my bot to be 1.0

**Comment by trevorsenior** [comment] 2015-02-09 17:37
@go1dfish This is the first endpoint that has an url parameter with a `{variable}/duplicates` I believe which may be causing an issue.

Does:

 ```javascript
reddit('/$article/duplicates/').listing({ $article: id });
```

work?

In between classes at the moment, but will write test cases for this endpoint later.

**Comment by damianb** [comment] 2015-02-09 17:38
Could be it, though I thought you recently patched in using things such as $subreddit in queries directly recently.  Ehh, if that's it, not that bad of a problem.

**Comment by trevorsenior** [comment] 2015-02-09 17:43
Yeah Snoocore does handle arbitrary things in the url now so his original writing of the call should have worked. This is probably a funky edge case it does not handle properly. :confused:

**Comment by go1dfish** [comment] 2015-02-09 18:54
reddit('/$article/duplicates/').listing({ $article: id });

I tried a few different variations and couldn't get it to work.  I looked at the JSON that got generated from the docs and tried messing around with what I gleaned from there but to no avail.

I also suspect it has to do with this url being not much like the others.

**Comment by trevorsenior** [comment] 2015-02-09 19:03
This is the first instance where there were two different paths that Snoocore could have chosen to traverse. The first one being 

https://www.reddit.com/dev/api#GET_{sort}

It chose to use that endpoint vs. the `{article}` one when determining which endpoint to use! I've adjusted the code to look at the *next* section of the path to check if it is valid as well before choosing it ([code](https://github.com/trevorsenior/snoocore/commit/d8a9b23019979bf55ebeac1e2d9944e9814e790f#diff-135365369312fbf369503c0296ea24eeR603)).

- - -

However, I still can't get this endpoint to function correctly.

I think that it **requires** OAuth, but even when authenticated I'm receiving HTTP 400 errors when trying to call it. I'll hop in the irc later and see if someone can provide an example of this endpoint.

**Comment by trevorsenior** [comment] 2015-02-09 20:07
I just noticed that the endpoint in the documentation is documented backwards.

It's documented as:

```javascript
/$article/duplicates
```

But the actual call is:

```javascript
/duplicates/$article
```

So when I pull the documentation from reddit to build the API, Snoocore is interpreting it backwards.

**Comment by trevorsenior** [comment] 2015-02-10 02:11
This should be fixed once https://github.com/reddit/reddit/pull/1253 gets resolved on reddit's end. I'll keep an eye on it & update this libraries endpoints when it hits. If it does not get updated in the next few days I can manually monkey patch the corrected endpoint in Snoocore.

**Comment by go1dfish** [comment] 2015-02-12 21:00
https://github.com/reddit/reddit/pull/1253 has been merged.

**Comment by trevorsenior** [comment] 2015-02-12 21:07
Thanks, just noticed that. Working on it now / will be pushed in 2.5.1 later today.

**Comment by trevorsenior** [comment] 2015-02-13 01:06
This endpoint is in `2.6.0` (Added in a new feature #86 so I had to bump the minor version).

However the `.listing` call can't be used yet because for some reason it returns *two* listings in an array. `.get` can be used for now which should remove the need for your `reddit.raw` `.get` call.

`.get` for the duplicates endpoint returns:

```javascript
[ { kind: 'Listing',
    data: { modhash: '', children: [Object], after: null, before: null } },
  { kind: 'Listing',
    data: { modhash: '', children: [], after: null, before: null } } ]
```

Which does not follow how every other listing endpoint works.

I'll have to clarify with the devs if this was intended / take a look at their code later.

**Comment by trevorsenior** [comment] 2015-02-18 21:45
Closing this issue. Opened a new issue (#95) that addresses the more specific problem.

**Closed by trevorsenior** 2015-02-18 21:45 UTC
Labels: bug
