### ISSUE TITLE
`deauth` fails with implicit OAuth

### ISSUE THREAD

**Issue by matthewgertner** [trevorsenior/snoocore#119] opened 2015-04-09 15:30 UTC
I'm using implicit OAuth to authenticate. If the user chooses to logout in my UI, I want to remove the token. However, when I call `deauth` as per the documentation, I get:

```XMLHttpRequest cannot load https://ssl.reddit.com/api/v1/revoke_token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.```

I'm running my code in the browser (client-side JS) and it seems like the API is triggering a CORS error. Is this a bug or am I missing something? I guess all I want to do is null out the `access_token` member. Of course I can just instantiate a new `Snoocore` instance, but I'm wondering if there is a clean way to do this.

**Comment by trevorsenior** [comment] 2015-04-09 19:26
You're not missing anything -- issue #93 covers the same topic. It's currently an issue with how reddit handles CORS and it affects Application only OAuth as well. It will hopefully be resolved soon. Take a look at https://github.com/reddit/reddit/issues/1285 for more information.

I'll go ahead and update the documentation on this in the meantime.

**Comment by matthewgertner** [comment] 2015-04-10 07:09
Can't you have `deauth` simply clear the `access_token` member if implicit OAuth was used to log in?

**Comment by trevorsenior** [comment] 2015-04-10 22:02
Yes, that would work; however, it will not invalidate the access token. What you suggested is what the deauth function does after revoking the access token, See:

https://github.com/trevorsenior/snoocore/blob/2.7.4/Snoocore.js#L872

For now, just replicate that behavior with:

```javascript
// instead of reddit.deauth(), use...
reddit._authData = {}; // clear internal auth data
```

This will work as a temporary solution for your problem as inelegant as it is. I want to have the deauth function actually revoke tokens & not hide the fact that it isn't. This is a bug on reddit's end, so it should fix itself once they push their patch to production. The good news is that [it is finished](https://github.com/reddit/reddit/compare/5f7526bc59...92cc540e16) for the most part, and should be working in the next week or so. 

I'll keep this issue open until it's working properly.

**Comment by matthewgertner** [comment] 2015-04-13 07:37
Cool, sounds like you are on top of this. Thanks for Snoocore by the way, it's great.

**Comment by trevorsenior** [comment] 2015-04-20 21:07
This should be fixed on reddit's end. I'll be testing this out in the 3.x.x branch in the next few days but it should also work in the current 2.x.x version of Snoocore.

**Comment by matthewgertner** [comment] 2015-04-24 19:22
Looks good on 2.x.x, thanks @trevorsenior!

**Closed** 2015-04-25 15:21 UTC
Labels: 2.x.x, bug

**Comment by matthewgertner** [comment] 2015-05-06 21:29
@trevorsenior I'm sure this was working for me, but now it's failing with a 401 when it tries to revoke the token. Maybe related to https://github.com/reddit/reddit/issues/1285 although it looks like the `OPTIONS` request is succeeding and the `POST` is 401ing. Did they change something on the server again?

**Comment by trevorsenior** [comment] 2015-05-07 01:30
Did you change your redirect URI recently? I'll give it a look in the sample app I wrote up and post back. What version of Snoocore are you using?

**Comment by trevorsenior** [comment] 2015-05-07 01:35
@matthewgertner It seems to work alright with the current version 3.0.0. You can checkout the [implicit oauth example](https://github.com/trevorsenior/snoocore-examples/blob/b28f1285c8251c90ea077587f4b29e85da383623/oauth-implicit.html).

Do you have any code I could look at or a small sample that reproduces this? This may be able to be "fixed" with a better error message because reddit can be cryptic at times :wink:

**Comment by matthewgertner** [comment] 2015-05-07 08:29
Oops, looks like it was user error on my part (accidently instantiated Snoocore without the consumer key in a specific case). I upgraded to 3.0.1 and with the improved error reporting, I found the problem immediately.

**Comment by trevorsenior** [comment] 2015-05-07 18:10
Ah glad to hear. 3.x.x has some user configuration checks as it's a common issue even when I use the library :wink:
